/*
 * Code for class WEL_DRAWING_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F188_4425(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4426(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4427(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4428(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4429(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4430(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4431(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4432(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4433(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4434(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4435(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4436(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4437(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4438(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4439(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4440(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4441(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4442(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4443(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4444(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4445(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4446(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4447(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4448(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4449(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4450(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4451(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4452(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4453(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4454(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4455(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4456(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4457(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4458(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4459(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4460(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4461(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4462(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4463(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4464(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4465(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4466(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4467(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4468(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4469(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4470(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4471(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4472(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4473(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4474(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4475(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4476(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4477(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4478(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4479(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4480(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4481(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4482(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4483(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4484(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4485(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4486(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4487(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4488(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4489(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4490(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4491(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4492(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4493(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4494(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4495(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4496(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4497(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4498(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4499(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4500(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4501(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4502(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4503(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4504(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4505(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4506(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4507(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4508(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4509(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4510(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4511(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4512(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4513(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4514(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4515(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4516(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4517(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4518(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4519(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4520(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4521(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4522(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4523(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4524(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4525(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4526(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4527(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4528(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4529(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4530(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4531(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4532(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4533(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4534(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4535(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4536(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4537(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4538(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4539(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4540(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4541(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4542(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4543(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4544(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4545(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4546(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4547(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4548(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4549(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4550(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4551(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4552(EIF_REFERENCE);
extern EIF_TYPED_VALUE F188_4553(EIF_REFERENCE, EIF_TYPED_VALUE);
extern void EIF_Minit188(void);

#ifdef __cplusplus
}
#endif

#include "wel.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_DRAWING_CONSTANTS}.dt_top */
EIF_TYPED_VALUE F188_4425 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_left */
EIF_TYPED_VALUE F188_4426 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_center */
EIF_TYPED_VALUE F188_4427 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_right */
EIF_TYPED_VALUE F188_4428 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_vcenter */
EIF_TYPED_VALUE F188_4429 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_bottom */
EIF_TYPED_VALUE F188_4430 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_wordbreak */
EIF_TYPED_VALUE F188_4431 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_singleline */
EIF_TYPED_VALUE F188_4432 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_expandtabs */
EIF_TYPED_VALUE F188_4433 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_tabstop */
EIF_TYPED_VALUE F188_4434 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_noclip */
EIF_TYPED_VALUE F188_4435 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_externalleading */
EIF_TYPED_VALUE F188_4436 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_calcrect */
EIF_TYPED_VALUE F188_4437 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_noprefix */
EIF_TYPED_VALUE F188_4438 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_internal */
EIF_TYPED_VALUE F188_4439 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dt_hideprefix */
EIF_TYPED_VALUE F188_4440 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1048576L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.di_compat */
EIF_TYPED_VALUE F188_4441 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.di_defaultsize */
EIF_TYPED_VALUE F188_4442 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.di_image */
EIF_TYPED_VALUE F188_4443 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.di_mask */
EIF_TYPED_VALUE F188_4444 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.di_normal */
EIF_TYPED_VALUE F188_4445 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfc_button */
EIF_TYPED_VALUE F188_4446 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfc_caption */
EIF_TYPED_VALUE F188_4447 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfc_menu */
EIF_TYPED_VALUE F188_4448 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfc_popupmenu */
EIF_TYPED_VALUE F188_4449 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfc_scroll */
EIF_TYPED_VALUE F188_4450 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_button3state */
EIF_TYPED_VALUE F188_4451 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_buttoncheck */
EIF_TYPED_VALUE F188_4452 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_buttonpush */
EIF_TYPED_VALUE F188_4453 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_buttonradio */
EIF_TYPED_VALUE F188_4454 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_buttonradioimage */
EIF_TYPED_VALUE F188_4455 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_buttonradiomask */
EIF_TYPED_VALUE F188_4456 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_captionclose */
EIF_TYPED_VALUE F188_4457 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_captionhelp */
EIF_TYPED_VALUE F188_4458 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_captionmax */
EIF_TYPED_VALUE F188_4459 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_captionmin */
EIF_TYPED_VALUE F188_4460 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_captionrestore */
EIF_TYPED_VALUE F188_4461 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_menuarrow */
EIF_TYPED_VALUE F188_4462 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_menuarrowright */
EIF_TYPED_VALUE F188_4463 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_menubullet */
EIF_TYPED_VALUE F188_4464 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_menucheck */
EIF_TYPED_VALUE F188_4465 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollcombobox */
EIF_TYPED_VALUE F188_4466 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrolldown */
EIF_TYPED_VALUE F188_4467 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollleft */
EIF_TYPED_VALUE F188_4468 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollright */
EIF_TYPED_VALUE F188_4469 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollsizegrip */
EIF_TYPED_VALUE F188_4470 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollsizegripright */
EIF_TYPED_VALUE F188_4471 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_scrollup */
EIF_TYPED_VALUE F188_4472 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_adjustrect */
EIF_TYPED_VALUE F188_4473 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8192L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_checked */
EIF_TYPED_VALUE F188_4474 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_flat */
EIF_TYPED_VALUE F188_4475 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16384L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_hot */
EIF_TYPED_VALUE F188_4476 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_inactive */
EIF_TYPED_VALUE F188_4477 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_mono */
EIF_TYPED_VALUE F188_4478 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_pushed */
EIF_TYPED_VALUE F188_4479 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dfcs_transparent */
EIF_TYPED_VALUE F188_4480 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bdr_raisedinner */
EIF_TYPED_VALUE F188_4481 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bdr_sunkeninner */
EIF_TYPED_VALUE F188_4482 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bdr_raisedouter */
EIF_TYPED_VALUE F188_4483 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bdr_sunkenouter */
EIF_TYPED_VALUE F188_4484 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.edge_bump */
EIF_TYPED_VALUE F188_4485 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.edge_etched */
EIF_TYPED_VALUE F188_4486 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.edge_raised */
EIF_TYPED_VALUE F188_4487 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.edge_sunken */
EIF_TYPED_VALUE F188_4488 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_adjust */
EIF_TYPED_VALUE F188_4489 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8192L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_bottom */
EIF_TYPED_VALUE F188_4490 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_bottomleft */
EIF_TYPED_VALUE F188_4491 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_bottomright */
EIF_TYPED_VALUE F188_4492 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_diagonal */
EIF_TYPED_VALUE F188_4493 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_diagonal_endbottomleft */
EIF_TYPED_VALUE F188_4494 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 25L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_diagonal_endbottomright */
EIF_TYPED_VALUE F188_4495 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_diagonal_endtopleft */
EIF_TYPED_VALUE F188_4496 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_diagonal_endtopright */
EIF_TYPED_VALUE F188_4497 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_flat */
EIF_TYPED_VALUE F188_4498 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16384L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_left */
EIF_TYPED_VALUE F188_4499 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_middle */
EIF_TYPED_VALUE F188_4500 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_mono */
EIF_TYPED_VALUE F188_4501 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_rect */
EIF_TYPED_VALUE F188_4502 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_right */
EIF_TYPED_VALUE F188_4503 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_soft */
EIF_TYPED_VALUE F188_4504 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_top */
EIF_TYPED_VALUE F188_4505 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_topleft */
EIF_TYPED_VALUE F188_4506 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.bf_topright */
EIF_TYPED_VALUE F188_4507 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dst_bitmap */
EIF_TYPED_VALUE F188_4508 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dst_complex */
EIF_TYPED_VALUE F188_4509 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dst_icon */
EIF_TYPED_VALUE F188_4510 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dst_prefixtext */
EIF_TYPED_VALUE F188_4511 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dst_text */
EIF_TYPED_VALUE F188_4512 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_disabled */
EIF_TYPED_VALUE F188_4513 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_hideprefix */
EIF_TYPED_VALUE F188_4514 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_mono */
EIF_TYPED_VALUE F188_4515 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_normal */
EIF_TYPED_VALUE F188_4516 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_prefixonly */
EIF_TYPED_VALUE F188_4517 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_right */
EIF_TYPED_VALUE F188_4518 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dss_union */
EIF_TYPED_VALUE F188_4519 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.srccopy */
EIF_TYPED_VALUE F188_4520 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13369376L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.srcpaint */
EIF_TYPED_VALUE F188_4521 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15597702L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.srcand */
EIF_TYPED_VALUE F188_4522 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8913094L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.srcinvert */
EIF_TYPED_VALUE F188_4523 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6684742L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.srcerase */
EIF_TYPED_VALUE F188_4524 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4457256L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.notsrccopy */
EIF_TYPED_VALUE F188_4525 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3342344L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.notsrcerase */
EIF_TYPED_VALUE F188_4526 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1114278L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.mergecopy */
EIF_TYPED_VALUE F188_4527 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12583114L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.mergepaint */
EIF_TYPED_VALUE F188_4528 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12255782L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.patcopy */
EIF_TYPED_VALUE F188_4529 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15728673L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.patpaint */
EIF_TYPED_VALUE F188_4530 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16452105L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.patinvert */
EIF_TYPED_VALUE F188_4531 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5898313L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.dstinvert */
EIF_TYPED_VALUE F188_4532 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5570569L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.blackness */
EIF_TYPED_VALUE F188_4533 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 66L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.whiteness */
EIF_TYPED_VALUE F188_4534 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16711778L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.maskpaint */
EIF_TYPED_VALUE F188_4535 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2229030L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_black */
EIF_TYPED_VALUE F188_4536 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_notmergepen */
EIF_TYPED_VALUE F188_4537 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_masknotpen */
EIF_TYPED_VALUE F188_4538 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_notcopypen */
EIF_TYPED_VALUE F188_4539 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_maskpennot */
EIF_TYPED_VALUE F188_4540 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_not */
EIF_TYPED_VALUE F188_4541 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_xorpen */
EIF_TYPED_VALUE F188_4542 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_notmaskpen */
EIF_TYPED_VALUE F188_4543 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_maskpen */
EIF_TYPED_VALUE F188_4544 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_notxorpen */
EIF_TYPED_VALUE F188_4545 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_nop */
EIF_TYPED_VALUE F188_4546 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_mergenotpen */
EIF_TYPED_VALUE F188_4547 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_copypen */
EIF_TYPED_VALUE F188_4548 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_mergepennot */
EIF_TYPED_VALUE F188_4549 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_mergepen */
EIF_TYPED_VALUE F188_4550 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.r2_white */
EIF_TYPED_VALUE F188_4551 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_DRAWING_CONSTANTS}.maskcopy */
EIF_TYPED_VALUE F188_4552 (EIF_REFERENCE Current)
{
	GTCX
	char *l_feature_name = "maskcopy";
	RTEX;
	EIF_INTEGER_32 Result = ((EIF_INTEGER_32) 0);
	
	RTSN;
	RTDA;
	RTLD;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_INT32, &Result);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 187, Current, 0, 0, 4388);
	RTSA(Dtype(Current));
	RTSC;
	RTME(Dtype(Current), 1);
	RTDBGEAA(187, Current, 4388);
	RTIV(Current, RTAL);
	Result = (EIF_INTEGER_32) MAKEROP4(SRCCOPY, PATCOPY);
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(1);
	RTDBGLE;
	RTMD(1);
	RTLE;
	RTLO(2);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_INT32; r.it_i4 = Result; return r; }
}

/* {WEL_DRAWING_CONSTANTS}.valid_rop2_constant */
EIF_TYPED_VALUE F188_4553 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "valid_rop2_constant";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_INTEGER_32 ti4_5;
	EIF_INTEGER_32 ti4_6;
	EIF_INTEGER_32 ti4_7;
	EIF_INTEGER_32 ti4_8;
	EIF_INTEGER_32 ti4_9;
	EIF_INTEGER_32 ti4_10;
	EIF_INTEGER_32 ti4_11;
	EIF_INTEGER_32 ti4_12;
	EIF_INTEGER_32 ti4_13;
	EIF_INTEGER_32 ti4_14;
	EIF_INTEGER_32 ti4_15;
	EIF_INTEGER_32 ti4_16;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 187, Current, 0, 1, 4389);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(187, Current, 4389);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(Current, 0, 0x04000000, 1,0); /* Result */
	
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 143, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 155, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 145, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 151, dtype))(Current)).it_i4);
	ti4_5 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 147, dtype))(Current)).it_i4);
	ti4_6 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 154, dtype))(Current)).it_i4);
	ti4_7 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 157, dtype))(Current)).it_i4);
	ti4_8 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 156, dtype))(Current)).it_i4);
	ti4_9 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 153, dtype))(Current)).it_i4);
	ti4_10 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 148, dtype))(Current)).it_i4);
	ti4_11 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 146, dtype))(Current)).it_i4);
	ti4_12 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 150, dtype))(Current)).it_i4);
	ti4_13 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 144, dtype))(Current)).it_i4);
	ti4_14 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 152, dtype))(Current)).it_i4);
	ti4_15 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 158, dtype))(Current)).it_i4);
	ti4_16 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(187, 149, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4)) || (EIF_BOOLEAN)(arg1 == ti4_5)) || (EIF_BOOLEAN)(arg1 == ti4_6)) || (EIF_BOOLEAN)(arg1 == ti4_7)) || (EIF_BOOLEAN)(arg1 == ti4_8)) || (EIF_BOOLEAN)(arg1 == ti4_9)) || (EIF_BOOLEAN)(arg1 == ti4_10)) || (EIF_BOOLEAN)(arg1 == ti4_11)) || (EIF_BOOLEAN)(arg1 == ti4_12)) || (EIF_BOOLEAN)(arg1 == ti4_13)) || (EIF_BOOLEAN)(arg1 == ti4_14)) || (EIF_BOOLEAN)(arg1 == ti4_15)) || (EIF_BOOLEAN)(arg1 == ti4_16));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

void EIF_Minit188 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
