INCLUDE_PATH =  -I"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\process\classic\windows\include" -I"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\wel\spec\windows\include" -I"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\vision2\spec\include"
SHELL = \bin\sh
CC = cl
CPP = cl
CFLAGS = -Od -Zi -MT -w -nologo -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_CRT_SECURE_NO_DEPRECATE -D_UNICODE -DUNICODE  -DEIF_THREADS  -DEIF_IEEE_BEHAVIOR -DWORKBENCH -I"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\spec\win64\include" -I. $(INCLUDE_PATH)
CPPFLAGS = -Od -Zi -MT -w -nologo -D_WIN32_WINNT=0x0500 -DWINVER=0x0500 -D_CRT_SECURE_NO_DEPRECATE -D_UNICODE -DUNICODE  -DEIF_THREADS  -DWORKBENCH -I"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\spec\win64\include" -I. $(INCLUDE_PATH)
LDFLAGS = -STACK:5000000 -NODEFAULTLIB:libc
CCLDFLAGS = -STACK:5000000 -NODEFAULTLIB:libc  -SUBSYSTEM:WINDOWS
LDSHAREDFLAGS =  -dll -incremental:no -NODEFAULTLIB:libc
EIFLIB = "C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\spec\win64\lib\msc\mtwkbench.lib"
EIFTEMPLATES = C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\config\win64\templates
LIBS = 
MAKE = nmake -s -nologo
AR = 
LD = 
MKDEP =   --
MV = copy
CP = copy
RANLIB = echo
RM = del
FILE_EXIST = if exist
RMDIR = rd
X2C = "C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\spec\win64\bin\x2c.exe"
SHAREDLINK = link
SHAREDLIBS = USER32.lib WS2_32.lib ADVAPI32.lib GDI32.lib SHELL32.lib MSIMG32.lib \
	COMDLG32.lib UUID.lib OLE32.lib OLEAUT32.lib COMCTL32.lib MPR.LIB SHLWAPI.LIB WINSPOOL.LIB 
SHARED_SUFFIX = .dll
COMMAND_MAKEFILE = 
START_TEST = if not exist finished 
END_TEST =  
CREATE_TEST = echo "finished" >> finished 
SYSTEM_IN_DYNAMIC_LIB = dose2012.dll 

.SUFFIXES:.cpp .obj 

.c.obj:
	$(CC) $(CFLAGS) -c $<

.cpp.obj:
	$(CPP) $(CPPFLAGS) -c $<

SUBDIRS = C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12 C13 C14 C15 C16 C17 C18 C19 C20 C21 C22 C23 C24 C25 C26 C27 C28 C29 C30 C31 C32 C33 C34 C35 C36 C37 C38 C39 C40 C41 C42 C43 C44 C45 C46 C47 C48 C49 C50 C51 C52 C53 E1

EXTERNALS =  \
	"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\net\spec\msc\win64\lib\mtnet.lib" \
	"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\wel\spec\msc\win64\lib\mtwel.lib" \
	"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\vision2\spec\msc\win64\lib\mtvision2.lib" \
	"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\vision2\spec\msc\win64\lib\libpng.lib" \
	"C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\library\vision2\spec\msc\win64\lib\zlib.lib"

all:: dose2012.exe
	echo done > completed.eif

C1\Cobj1.lib: Makefile E1\estructure.h
	cd C1
	$(START_TEST) $(MAKE) Cobj1.lib $(END_TEST)
	cd ..

C2\Cobj2.lib: Makefile E1\estructure.h
	cd C2
	$(START_TEST) $(MAKE) Cobj2.lib $(END_TEST)
	cd ..

C3\Cobj3.lib: Makefile E1\estructure.h
	cd C3
	$(START_TEST) $(MAKE) Cobj3.lib $(END_TEST)
	cd ..

C4\Cobj4.lib: Makefile E1\estructure.h
	cd C4
	$(START_TEST) $(MAKE) Cobj4.lib $(END_TEST)
	cd ..

C5\Cobj5.lib: Makefile E1\estructure.h
	cd C5
	$(START_TEST) $(MAKE) Cobj5.lib $(END_TEST)
	cd ..

C6\Cobj6.lib: Makefile E1\estructure.h
	cd C6
	$(START_TEST) $(MAKE) Cobj6.lib $(END_TEST)
	cd ..

C7\Cobj7.lib: Makefile E1\estructure.h
	cd C7
	$(START_TEST) $(MAKE) Cobj7.lib $(END_TEST)
	cd ..

C8\Cobj8.lib: Makefile E1\estructure.h
	cd C8
	$(START_TEST) $(MAKE) Cobj8.lib $(END_TEST)
	cd ..

C9\Cobj9.lib: Makefile E1\estructure.h
	cd C9
	$(START_TEST) $(MAKE) Cobj9.lib $(END_TEST)
	cd ..

C10\Cobj10.lib: Makefile E1\estructure.h
	cd C10
	$(START_TEST) $(MAKE) Cobj10.lib $(END_TEST)
	cd ..

C11\Cobj11.lib: Makefile E1\estructure.h
	cd C11
	$(START_TEST) $(MAKE) Cobj11.lib $(END_TEST)
	cd ..

C12\Cobj12.lib: Makefile E1\estructure.h
	cd C12
	$(START_TEST) $(MAKE) Cobj12.lib $(END_TEST)
	cd ..

C13\Cobj13.lib: Makefile E1\estructure.h
	cd C13
	$(START_TEST) $(MAKE) Cobj13.lib $(END_TEST)
	cd ..

C14\Cobj14.lib: Makefile E1\estructure.h
	cd C14
	$(START_TEST) $(MAKE) Cobj14.lib $(END_TEST)
	cd ..

C15\Cobj15.lib: Makefile E1\estructure.h
	cd C15
	$(START_TEST) $(MAKE) Cobj15.lib $(END_TEST)
	cd ..

C16\Cobj16.lib: Makefile E1\estructure.h
	cd C16
	$(START_TEST) $(MAKE) Cobj16.lib $(END_TEST)
	cd ..

C17\Cobj17.lib: Makefile E1\estructure.h
	cd C17
	$(START_TEST) $(MAKE) Cobj17.lib $(END_TEST)
	cd ..

C18\Cobj18.lib: Makefile E1\estructure.h
	cd C18
	$(START_TEST) $(MAKE) Cobj18.lib $(END_TEST)
	cd ..

C19\Cobj19.lib: Makefile E1\estructure.h
	cd C19
	$(START_TEST) $(MAKE) Cobj19.lib $(END_TEST)
	cd ..

C20\Cobj20.lib: Makefile E1\estructure.h
	cd C20
	$(START_TEST) $(MAKE) Cobj20.lib $(END_TEST)
	cd ..

C21\Cobj21.lib: Makefile E1\estructure.h
	cd C21
	$(START_TEST) $(MAKE) Cobj21.lib $(END_TEST)
	cd ..

C22\Cobj22.lib: Makefile E1\estructure.h
	cd C22
	$(START_TEST) $(MAKE) Cobj22.lib $(END_TEST)
	cd ..

C23\Cobj23.lib: Makefile E1\estructure.h
	cd C23
	$(START_TEST) $(MAKE) Cobj23.lib $(END_TEST)
	cd ..

C24\Cobj24.lib: Makefile E1\estructure.h
	cd C24
	$(START_TEST) $(MAKE) Cobj24.lib $(END_TEST)
	cd ..

C25\Cobj25.lib: Makefile E1\estructure.h
	cd C25
	$(START_TEST) $(MAKE) Cobj25.lib $(END_TEST)
	cd ..

C26\Cobj26.lib: Makefile E1\estructure.h
	cd C26
	$(START_TEST) $(MAKE) Cobj26.lib $(END_TEST)
	cd ..

C27\Cobj27.lib: Makefile E1\estructure.h
	cd C27
	$(START_TEST) $(MAKE) Cobj27.lib $(END_TEST)
	cd ..

C28\Cobj28.lib: Makefile E1\estructure.h
	cd C28
	$(START_TEST) $(MAKE) Cobj28.lib $(END_TEST)
	cd ..

C29\Cobj29.lib: Makefile E1\estructure.h
	cd C29
	$(START_TEST) $(MAKE) Cobj29.lib $(END_TEST)
	cd ..

C30\Cobj30.lib: Makefile E1\estructure.h
	cd C30
	$(START_TEST) $(MAKE) Cobj30.lib $(END_TEST)
	cd ..

C31\Cobj31.lib: Makefile E1\estructure.h
	cd C31
	$(START_TEST) $(MAKE) Cobj31.lib $(END_TEST)
	cd ..

C32\Cobj32.lib: Makefile E1\estructure.h
	cd C32
	$(START_TEST) $(MAKE) Cobj32.lib $(END_TEST)
	cd ..

C33\Cobj33.lib: Makefile E1\estructure.h
	cd C33
	$(START_TEST) $(MAKE) Cobj33.lib $(END_TEST)
	cd ..

C34\Cobj34.lib: Makefile E1\estructure.h
	cd C34
	$(START_TEST) $(MAKE) Cobj34.lib $(END_TEST)
	cd ..

C35\Cobj35.lib: Makefile E1\estructure.h
	cd C35
	$(START_TEST) $(MAKE) Cobj35.lib $(END_TEST)
	cd ..

C36\Cobj36.lib: Makefile E1\estructure.h
	cd C36
	$(START_TEST) $(MAKE) Cobj36.lib $(END_TEST)
	cd ..

C37\Cobj37.lib: Makefile E1\estructure.h
	cd C37
	$(START_TEST) $(MAKE) Cobj37.lib $(END_TEST)
	cd ..

C38\Cobj38.lib: Makefile E1\estructure.h
	cd C38
	$(START_TEST) $(MAKE) Cobj38.lib $(END_TEST)
	cd ..

C39\Cobj39.lib: Makefile E1\estructure.h
	cd C39
	$(START_TEST) $(MAKE) Cobj39.lib $(END_TEST)
	cd ..

C40\Cobj40.lib: Makefile E1\estructure.h
	cd C40
	$(START_TEST) $(MAKE) Cobj40.lib $(END_TEST)
	cd ..

C41\Cobj41.lib: Makefile E1\estructure.h
	cd C41
	$(START_TEST) $(MAKE) Cobj41.lib $(END_TEST)
	cd ..

C42\Cobj42.lib: Makefile E1\estructure.h
	cd C42
	$(START_TEST) $(MAKE) Cobj42.lib $(END_TEST)
	cd ..

C43\Cobj43.lib: Makefile E1\estructure.h
	cd C43
	$(START_TEST) $(MAKE) Cobj43.lib $(END_TEST)
	cd ..

C44\Cobj44.lib: Makefile E1\estructure.h
	cd C44
	$(START_TEST) $(MAKE) Cobj44.lib $(END_TEST)
	cd ..

C45\Cobj45.lib: Makefile E1\estructure.h
	cd C45
	$(START_TEST) $(MAKE) Cobj45.lib $(END_TEST)
	cd ..

C46\Cobj46.lib: Makefile E1\estructure.h
	cd C46
	$(START_TEST) $(MAKE) Cobj46.lib $(END_TEST)
	cd ..

C47\Cobj47.lib: Makefile E1\estructure.h
	cd C47
	$(START_TEST) $(MAKE) Cobj47.lib $(END_TEST)
	cd ..

C48\Cobj48.lib: Makefile E1\estructure.h
	cd C48
	$(START_TEST) $(MAKE) Cobj48.lib $(END_TEST)
	cd ..

C49\Cobj49.lib: Makefile E1\estructure.h
	cd C49
	$(START_TEST) $(MAKE) Cobj49.lib $(END_TEST)
	cd ..

C50\Cobj50.lib: Makefile E1\estructure.h
	cd C50
	$(START_TEST) $(MAKE) Cobj50.lib $(END_TEST)
	cd ..

C51\Cobj51.lib: Makefile E1\estructure.h
	cd C51
	$(START_TEST) $(MAKE) Cobj51.lib $(END_TEST)
	cd ..

C52\Cobj52.lib: Makefile E1\estructure.h
	cd C52
	$(START_TEST) $(MAKE) Cobj52.lib $(END_TEST)
	cd ..

C53\Cobj53.lib: Makefile E1\estructure.h
	cd C53
	$(START_TEST) $(MAKE) Cobj53.lib $(END_TEST)
	cd ..

E1\emain.obj:  Makefile E1\Makefile
	$(CP) "$(EIFTEMPLATES)\emain.template" E1\emain.c
	cd E1
	$(START_TEST) $(MAKE) emain.obj  $(END_TEST)
	cd ..

E1\eoption.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) eoption.obj  $(END_TEST)
	cd ..

E1\epattern.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) epattern.obj  $(END_TEST)
	cd ..

E1\efrozen.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) efrozen.obj  $(END_TEST)
	cd ..

E1\ecall.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) ecall.obj  $(END_TEST)
	cd ..

E1\eplug.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) eplug.obj  $(END_TEST)
	cd ..

E1\eskelet.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) eskelet.obj  $(END_TEST)
	cd ..

E1\enames.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) enames.obj  $(END_TEST)
	cd ..

E1\evisib.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) evisib.obj  $(END_TEST)
	cd ..

E1\ececil.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) ececil.obj  $(END_TEST)
	cd ..

E1\einit.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) einit.obj  $(END_TEST)
	cd ..

E1\eparents.obj : Makefile E1\Makefile E1\estructure.h
	cd E1
	$(START_TEST) $(MAKE) eparents.obj  $(END_TEST)
	cd ..

OBJECTS = E1\eparents.obj  E1\einit.obj  E1\ececil.obj  E1\evisib.obj  E1\enames.obj  E1\eskelet.obj  E1\eplug.obj  E1\ecall.obj  E1\efrozen.obj  E1\epattern.obj  E1\eoption.obj  C53\Cobj53.lib C52\Cobj52.lib C51\Cobj51.lib C50\Cobj50.lib C49\Cobj49.lib C48\Cobj48.lib C47\Cobj47.lib C46\Cobj46.lib C45\Cobj45.lib C44\Cobj44.lib C43\Cobj43.lib C42\Cobj42.lib C41\Cobj41.lib C40\Cobj40.lib C39\Cobj39.lib C38\Cobj38.lib C37\Cobj37.lib C36\Cobj36.lib C35\Cobj35.lib C34\Cobj34.lib C33\Cobj33.lib C32\Cobj32.lib C31\Cobj31.lib C30\Cobj30.lib C29\Cobj29.lib C28\Cobj28.lib C27\Cobj27.lib C26\Cobj26.lib C25\Cobj25.lib C24\Cobj24.lib C23\Cobj23.lib C22\Cobj22.lib C21\Cobj21.lib C20\Cobj20.lib C19\Cobj19.lib C18\Cobj18.lib C17\Cobj17.lib C16\Cobj16.lib C15\Cobj15.lib C14\Cobj14.lib C13\Cobj13.lib C12\Cobj12.lib C11\Cobj11.lib C10\Cobj10.lib C9\Cobj9.lib C8\Cobj8.lib C7\Cobj7.lib C6\Cobj6.lib C5\Cobj5.lib C4\Cobj4.lib C3\Cobj3.lib C2\Cobj2.lib C1\Cobj1.lib 

C_OBJECTS = C53\Cobj53.lib C52\Cobj52.lib C51\Cobj51.lib C50\Cobj50.lib C49\Cobj49.lib C48\Cobj48.lib C47\Cobj47.lib C46\Cobj46.lib C45\Cobj45.lib C44\Cobj44.lib C43\Cobj43.lib C42\Cobj42.lib C41\Cobj41.lib C40\Cobj40.lib C39\Cobj39.lib C38\Cobj38.lib C37\Cobj37.lib C36\Cobj36.lib C35\Cobj35.lib C34\Cobj34.lib C33\Cobj33.lib C32\Cobj32.lib C31\Cobj31.lib C30\Cobj30.lib C29\Cobj29.lib C28\Cobj28.lib C27\Cobj27.lib C26\Cobj26.lib C25\Cobj25.lib C24\Cobj24.lib C23\Cobj23.lib C22\Cobj22.lib C21\Cobj21.lib C20\Cobj20.lib C19\Cobj19.lib C18\Cobj18.lib C17\Cobj17.lib C16\Cobj16.lib C15\Cobj15.lib C14\Cobj14.lib C13\Cobj13.lib C12\Cobj12.lib C11\Cobj11.lib C10\Cobj10.lib C9\Cobj9.lib C8\Cobj8.lib C7\Cobj7.lib C6\Cobj6.lib C5\Cobj5.lib C4\Cobj4.lib C3\Cobj3.lib C2\Cobj2.lib C1\Cobj1.lib 

EOBJECTS = E1\eparents.obj  E1\einit.obj  E1\ececil.obj  E1\evisib.obj  E1\enames.obj  E1\eskelet.obj  E1\eplug.obj  E1\ecall.obj  E1\efrozen.obj  E1\epattern.obj  E1\eoption.obj  




dose2012.exe: dose2012.lnk dose2012.res
	$(COMMAND_MAKEFILE)
	link @dose2012.lnk

..\..\..\dose2012.rc:
	if not exist ..\..\..\dose2012.rc $(MV) "C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\config\win64\msc\eiffel.rc" ..\..\..\dose2012.rc

dose2012.res: ..\..\..\dose2012.rc Makefile
	rc -r -fodose2012.res ..\..\..\dose2012.rc

dose2012.lnk: $(OBJECTS) e1\emain.obj dose2012.res Makefile
	if exist $@ $(RM) $@
	@echo $(LDFLAGS) $(CCLDFLAGS) -OUT:dose2012.exe > $@
	@echo e1\emain.obj >> $@
	@echo $(EIFLIB) $(EXTERNALS) >> $@
	@echo USER32.lib WS2_32.lib ADVAPI32.lib GDI32.lib SHELL32.lib MSIMG32.lib \
	COMDLG32.lib UUID.lib OLE32.lib OLEAUT32.lib COMCTL32.lib MPR.LIB SHLWAPI.LIB WINSPOOL.LIB $(ISE_SHAREDLIBS) $(PRECOMP_OBJECTS) >> $@
	@echo dose2012.res >> $@
	echo E1\eparents.obj  E1\einit.obj  E1\ececil.obj  E1\evisib.obj  E1\enames.obj   >> $@ 
	echo E1\eskelet.obj  E1\eplug.obj  E1\ecall.obj  E1\efrozen.obj  E1\epattern.obj   >> $@ 
	echo E1\eoption.obj  C53\Cobj53.lib C52\Cobj52.lib C51\Cobj51.lib C50\Cobj50.lib  >> $@ 
	echo C49\Cobj49.lib C48\Cobj48.lib C47\Cobj47.lib C46\Cobj46.lib C45\Cobj45.lib  >> $@ 
	echo C44\Cobj44.lib C43\Cobj43.lib C42\Cobj42.lib C41\Cobj41.lib C40\Cobj40.lib  >> $@ 
	echo C39\Cobj39.lib C38\Cobj38.lib C37\Cobj37.lib C36\Cobj36.lib C35\Cobj35.lib  >> $@ 
	echo C34\Cobj34.lib C33\Cobj33.lib C32\Cobj32.lib C31\Cobj31.lib C30\Cobj30.lib  >> $@ 
	echo C29\Cobj29.lib C28\Cobj28.lib C27\Cobj27.lib C26\Cobj26.lib C25\Cobj25.lib  >> $@ 
	echo C24\Cobj24.lib C23\Cobj23.lib C22\Cobj22.lib C21\Cobj21.lib C20\Cobj20.lib  >> $@ 
	echo C19\Cobj19.lib C18\Cobj18.lib C17\Cobj17.lib C16\Cobj16.lib C15\Cobj15.lib  >> $@ 
	echo C14\Cobj14.lib C13\Cobj13.lib C12\Cobj12.lib C11\Cobj11.lib C10\Cobj10.lib  >> $@ 
	echo C9\Cobj9.lib C8\Cobj8.lib C7\Cobj7.lib C6\Cobj6.lib C5\Cobj5.lib  >> $@ 
	echo C4\Cobj4.lib C3\Cobj3.lib C2\Cobj2.lib C1\Cobj1.lib  >> $@ 


RCECIL = MTwmalloc.obj MTwgarcol.obj MTwlocal.obj MTwexcept.obj MTwstore.obj \
	MTwretrieve.obj MTwhash.obj MTwtraverse.obj MTwhashin.obj MTwtools.obj \
	MTwinternal.obj MTwplug.obj MTwcopy.obj MTwequal.obj MTwlmalloc.obj MTwout.obj \
	MTwtimer.obj MTwurgent.obj MTwsig.obj MTwhector.obj MTwcecil.obj MTwbits.obj \
	MTwfile.obj MTwdir.obj MTwmisc.obj MTwerror.obj MTwumain.obj MTwmemory.obj \
	MTwargv.obj MTwboolstr.obj MTwsearch.obj MTwmain.obj MTdebug.obj MTinterp.obj \
	MTwoption.obj MTupdate.obj MTwbench.obj MTwrun_idr.obj MTwcompress.obj \
	MTwconsole.obj MTwpath_name.obj MTwobject_id.obj MTweif_threads.obj \
	MTwgen_conf.obj MTweif_type_id.obj MTwrout_obj.obj MTweif_project.obj \
	MTidrs.obj MTwposix_threads.obj MTnetwork.obj mtipc.obj MTwscoop.obj 


#STATIC_CECIL PART
STATIC_CECIL = libdose2012.lib
cecil: $(STATIC_CECIL)
$(STATIC_CECIL): $(OBJECTS) $(EIFLIB) 
	if exist $@ $(RM) $@
	lib -nologo -OUT:$(STATIC_CECIL) $(OBJECTS) $(EXTERNALS) $(EIFLIB) $(PRECOMP_OBJECTS)



#SHARED_CECIL PART
SHARED_CECIL = libdose2012$(SHARED_SUFFIX)
dynamic_cecil: $(SHARED_CECIL) 
DEF_FILE= c_dose2012.def 
c_dose2012.def: 
	if exist $@ $(RM) $@
	echo LIBRARY libdose2012.dll > $@
	type "C:\Program Files\Eiffel Software\EiffelStudio 7.1 GPL\studio\config\win64\templates\cecil.def"  >> $@

SHARED_CECIL_OBJECT = $(OBJECTS) \
		E1/emain.obj
SHAREDFLAGS = $(LDSHAREDFLAGS) \
	/def:$(DEF_FILE) \
	/OUT:$(SHARED_CECIL) /IMPLIB:c_dll_dose2012.lib

$(SHARED_CECIL): $(SHARED_CECIL_OBJECT)  $(DEF_FILE)
	if exist $(SHARED_CECIL) del $(SHARED_CECIL)
	$(SHAREDLINK) $(SHAREDFLAGS) $(SHARED_CECIL_OBJECT) $(PRECOMP_OBJECTS) $(EXTERNALS) $(EIFLIB) $(SHAREDLIBS) 

#SYSTEM_IN_DYNAMIC_LIB PART

DEF_FILE= dose2012.def
dynlib: $(SYSTEM_IN_DYNAMIC_LIB) 
E1\egc_dynlib.obj: Makefile E1\Makefile
	$(CP) "$(EIFTEMPLATES)\egc_dynlib.template" E1\egc_dynlib.c
	cd E1
	$(MAKE) egc_dynlib.obj
	cd ..
E1\edynlib.obj: Makefile E1\Makefile E1\edynlib.c 
	cd E1
	$(MAKE) edynlib.obj
	cd ..

SYSTEM_IN_DYNAMIC_LIB_OBJ = $(OBJECTS) \
		E1\edynlib.obj E1\egc_dynlib.obj 
DYNLIBSHAREDFLAGS = $(LDSHAREDFLAGS) \
	/def:$(DEF_FILE) \
	/OUT:$(SYSTEM_IN_DYNAMIC_LIB) /IMPLIB:dll_dose2012.lib dose2012.res

$(SYSTEM_IN_DYNAMIC_LIB): $(SYSTEM_IN_DYNAMIC_LIB_OBJ)  $(DEF_FILE)
	if exist $(SYSTEM_IN_DYNAMIC_LIB) del $(SYSTEM_IN_DYNAMIC_LIB)
	$(SHAREDLINK) $(DYNLIBSHAREDFLAGS) $(SYSTEM_IN_DYNAMIC_LIB_OBJ) $(PRECOMP_OBJECTS) $(EXTERNALS) $(EIFLIB) $(SHAREDLIBS) 



clean: sub_clean local_clean
clobber: sub_clobber local_clobber

local_clean::
	$(RM) core finished *.obj *.so *.a

local_clobber:: local_clean
	$(RM) Makefile config.sh finish_freezing

sub_clean::
	for i in $(SUBDIRS); \
	do \
		if [ -r $$i\Makefile ]; then \
			(cd $$i ; $(MAKE) clean); \
		fi; \
	done

sub_clobber::
	for i in $(SUBDIRS); \
	do \
		if [ -r $$i\Makefile ]; then \
			(cd $$i ; $(MAKE) clobber); \
		fi; \
	done

