/*
 * Generated by ISE 7.1.8.8986 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F784_15171();
extern void F788_15431();
extern void F783_15119();
extern void F787_15340();
extern void F1233_9150();
extern void F1221_15025();
extern void F236_5271();
extern EIF_REFERENCE F236_5258();
extern EIF_BOOLEAN F236_5270();
extern EIF_BOOLEAN F236_5275();
extern void F236_5280();
extern void F236_5281();
extern void F236_5282();
extern void F354_6851();
extern EIF_TYPED_VALUE F354_6852();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F784_15171;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F783_15119;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F1233_9150;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F788_15431;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F787_15340;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F1221_15025;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F236_5271;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F236_5270;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F236_5258;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F236_5275;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F236_5280;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F236_5281;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F236_5282;

	egc_str_dtype = 787;

	egc_str32_dtype = 786;
	egc_arr_dtype = 1232;
	egc_tup_dtype = 734;
	egc_disp_rout_id = 9265;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)1423;
	egc_sp_wchar = (EIF_TYPE_INDEX)1560;
	egc_sp_bool = (EIF_TYPE_INDEX)1488;
	egc_sp_uint8 = (EIF_TYPE_INDEX)1374;
	egc_sp_uint16 = (EIF_TYPE_INDEX)65535;
	egc_sp_uint32 = (EIF_TYPE_INDEX)65535;
	egc_sp_uint64 = (EIF_TYPE_INDEX)1323;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)1304;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)1678;
	egc_sp_real64 = (EIF_TYPE_INDEX)1406;
	egc_sp_pointer = (EIF_TYPE_INDEX)1602;
	egc_sp_ref = (EIF_TYPE_INDEX)1225;

	egc_uint8_ref_dtype = 756;
	egc_uint16_ref_dtype = 753;
	egc_uint32_ref_dtype = 750;
	egc_uint64_ref_dtype = 747;
	egc_int8_ref_dtype = 744;
	egc_int16_ref_dtype = 741;
	egc_int32_ref_dtype = 738;
	egc_int64_ref_dtype = 735;
	egc_bool_ref_dtype = 768;
	egc_real32_ref_dtype = 759;
	egc_char_ref_dtype = 765;
	egc_wchar_ref_dtype = 771;
	egc_real64_ref_dtype = 762;
	egc_point_ref_dtype = 777;

	egc_uint8_dtype = 757;
	egc_uint16_dtype = 754;
	egc_uint32_dtype = 751;
	egc_uint64_dtype = 748;
	egc_int8_dtype = 745;
	egc_int16_dtype = 742;
	egc_int32_dtype = 739;
	egc_int64_dtype = 736;
	egc_bool_dtype = 769;
	egc_real32_dtype = 760;
	egc_char_dtype = 766;
	egc_wchar_dtype = 772;
	egc_real64_dtype = 763;
	egc_point_dtype = 778;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 415;
	egc_except_emnger_dtype = 235;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;

	egc_fcall = egc_fcall_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "dose2012";
	egc_system_location = "C:\\Users\\Lorenzo\\Desktop\\src\\EIFGENs\\dose2012\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1352755746;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1732;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcorigin = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcoffset = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcorigin[0] = 1;
	egc_rcoffset[0] = 0;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcorigin[1] = 2;
	egc_rcoffset[1] = 0;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcorigin[2] = 3;
	egc_rcoffset[2] = 0;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 353;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F354_6851;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F354_6852;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 808; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 511; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 1214; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
