/*
 * Code for class WEL_INPUT_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F198_4668(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4669(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4670(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4671(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4672(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4673(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4674(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4675(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4676(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4677(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4678(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4679(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4680(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4681(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4682(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4683(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4684(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4685(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4686(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4687(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4688(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4689(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4690(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4691(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4692(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4693(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4694(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4695(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4696(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4697(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4698(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4699(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4700(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4701(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4702(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4703(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4704(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4705(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4706(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4707(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4708(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4709(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4710(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4711(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4712(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4713(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4714(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4715(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4716(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4717(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4718(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4719(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4720(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4721(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4722(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4723(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4724(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4725(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4726(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4727(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4728(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4729(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4730(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4731(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4732(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4733(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4734(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4735(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4736(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4737(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4738(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4739(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4740(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4741(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4742(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4743(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4744(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4745(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4746(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4747(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4748(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4749(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4750(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4751(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4752(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4753(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4754(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4755(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4756(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4757(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4758(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4759(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4760(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4761(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4762(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4763(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4764(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4765(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4766(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4767(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4768(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4769(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4770(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4771(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4772(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4773(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4774(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4775(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4776(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4777(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4778(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4779(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4780(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4781(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4782(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4783(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4784(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4785(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4786(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4787(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4788(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4789(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4790(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4791(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4792(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4793(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4794(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4795(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4796(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4797(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4798(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4799(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4800(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4801(EIF_REFERENCE);
extern EIF_TYPED_VALUE F198_4802(EIF_REFERENCE);
extern void EIF_Minit198(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_INPUT_CONSTANTS}.ma_activate */
EIF_TYPED_VALUE F198_4668 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.ma_activateandeat */
EIF_TYPED_VALUE F198_4669 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.ma_noactivate */
EIF_TYPED_VALUE F198_4670 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.ma_noactivateandeat */
EIF_TYPED_VALUE F198_4671 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mk_control */
EIF_TYPED_VALUE F198_4672 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mk_lbutton */
EIF_TYPED_VALUE F198_4673 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mk_mbutton */
EIF_TYPED_VALUE F198_4674 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mk_rbutton */
EIF_TYPED_VALUE F198_4675 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mk_shift */
EIF_TYPED_VALUE F198_4676 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_lbutton */
EIF_TYPED_VALUE F198_4677 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_rbutton */
EIF_TYPED_VALUE F198_4678 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_cancel */
EIF_TYPED_VALUE F198_4679 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_mbutton */
EIF_TYPED_VALUE F198_4680 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_back */
EIF_TYPED_VALUE F198_4681 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_tab */
EIF_TYPED_VALUE F198_4682 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_clear */
EIF_TYPED_VALUE F198_4683 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_return */
EIF_TYPED_VALUE F198_4684 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_shift */
EIF_TYPED_VALUE F198_4685 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_control */
EIF_TYPED_VALUE F198_4686 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_menu */
EIF_TYPED_VALUE F198_4687 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_pause */
EIF_TYPED_VALUE F198_4688 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_capital */
EIF_TYPED_VALUE F198_4689 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_escape */
EIF_TYPED_VALUE F198_4690 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_space */
EIF_TYPED_VALUE F198_4691 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_prior */
EIF_TYPED_VALUE F198_4692 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 33L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_next */
EIF_TYPED_VALUE F198_4693 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 34L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_end */
EIF_TYPED_VALUE F198_4694 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 35L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_home */
EIF_TYPED_VALUE F198_4695 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 36L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_left */
EIF_TYPED_VALUE F198_4696 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 37L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_up */
EIF_TYPED_VALUE F198_4697 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 38L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_right */
EIF_TYPED_VALUE F198_4698 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 39L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_down */
EIF_TYPED_VALUE F198_4699 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 40L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_select */
EIF_TYPED_VALUE F198_4700 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 41L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_print */
EIF_TYPED_VALUE F198_4701 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 42L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_execute */
EIF_TYPED_VALUE F198_4702 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 43L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_snapshot */
EIF_TYPED_VALUE F198_4703 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 44L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_insert */
EIF_TYPED_VALUE F198_4704 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 45L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_delete */
EIF_TYPED_VALUE F198_4705 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 46L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_help */
EIF_TYPED_VALUE F198_4706 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 47L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad0 */
EIF_TYPED_VALUE F198_4707 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 96L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad1 */
EIF_TYPED_VALUE F198_4708 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 97L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad2 */
EIF_TYPED_VALUE F198_4709 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 98L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad3 */
EIF_TYPED_VALUE F198_4710 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 99L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad4 */
EIF_TYPED_VALUE F198_4711 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 100L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad5 */
EIF_TYPED_VALUE F198_4712 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 101L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad6 */
EIF_TYPED_VALUE F198_4713 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 102L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad7 */
EIF_TYPED_VALUE F198_4714 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 103L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad8 */
EIF_TYPED_VALUE F198_4715 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 104L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numpad9 */
EIF_TYPED_VALUE F198_4716 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 105L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_multiply */
EIF_TYPED_VALUE F198_4717 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 106L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_add */
EIF_TYPED_VALUE F198_4718 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 107L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_separator */
EIF_TYPED_VALUE F198_4719 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 108L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_subtract */
EIF_TYPED_VALUE F198_4720 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 109L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_decimal */
EIF_TYPED_VALUE F198_4721 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 110L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_divide */
EIF_TYPED_VALUE F198_4722 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 111L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f1 */
EIF_TYPED_VALUE F198_4723 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 112L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f2 */
EIF_TYPED_VALUE F198_4724 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 113L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f3 */
EIF_TYPED_VALUE F198_4725 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 114L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f4 */
EIF_TYPED_VALUE F198_4726 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 115L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f5 */
EIF_TYPED_VALUE F198_4727 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 116L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f6 */
EIF_TYPED_VALUE F198_4728 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 117L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f7 */
EIF_TYPED_VALUE F198_4729 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 118L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f8 */
EIF_TYPED_VALUE F198_4730 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 119L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f9 */
EIF_TYPED_VALUE F198_4731 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 120L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f10 */
EIF_TYPED_VALUE F198_4732 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 121L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f11 */
EIF_TYPED_VALUE F198_4733 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 122L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f12 */
EIF_TYPED_VALUE F198_4734 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 123L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f13 */
EIF_TYPED_VALUE F198_4735 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 124L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f14 */
EIF_TYPED_VALUE F198_4736 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 125L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f15 */
EIF_TYPED_VALUE F198_4737 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 126L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f16 */
EIF_TYPED_VALUE F198_4738 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 127L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f17 */
EIF_TYPED_VALUE F198_4739 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f18 */
EIF_TYPED_VALUE F198_4740 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 129L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f19 */
EIF_TYPED_VALUE F198_4741 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 130L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f20 */
EIF_TYPED_VALUE F198_4742 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f21 */
EIF_TYPED_VALUE F198_4743 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 132L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f22 */
EIF_TYPED_VALUE F198_4744 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 133L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f23 */
EIF_TYPED_VALUE F198_4745 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 134L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f24 */
EIF_TYPED_VALUE F198_4746 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 135L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_numlock */
EIF_TYPED_VALUE F198_4747 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 144L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_scroll */
EIF_TYPED_VALUE F198_4748 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 145L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_lshift */
EIF_TYPED_VALUE F198_4749 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 160L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_rshift */
EIF_TYPED_VALUE F198_4750 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 161L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_lcontrol */
EIF_TYPED_VALUE F198_4751 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 162L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_rcontrol */
EIF_TYPED_VALUE F198_4752 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 163L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_lmenu */
EIF_TYPED_VALUE F198_4753 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 164L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_rmenu */
EIF_TYPED_VALUE F198_4754 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 165L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_0 */
EIF_TYPED_VALUE F198_4755 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 48L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_1 */
EIF_TYPED_VALUE F198_4756 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 49L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_2 */
EIF_TYPED_VALUE F198_4757 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 50L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_3 */
EIF_TYPED_VALUE F198_4758 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 51L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_4 */
EIF_TYPED_VALUE F198_4759 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 52L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_5 */
EIF_TYPED_VALUE F198_4760 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 53L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_6 */
EIF_TYPED_VALUE F198_4761 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 54L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_7 */
EIF_TYPED_VALUE F198_4762 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 55L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_8 */
EIF_TYPED_VALUE F198_4763 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 56L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_9 */
EIF_TYPED_VALUE F198_4764 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 57L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_a */
EIF_TYPED_VALUE F198_4765 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_b */
EIF_TYPED_VALUE F198_4766 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 66L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_c */
EIF_TYPED_VALUE F198_4767 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 67L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_d */
EIF_TYPED_VALUE F198_4768 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 68L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_e */
EIF_TYPED_VALUE F198_4769 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 69L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_f */
EIF_TYPED_VALUE F198_4770 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 70L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_g */
EIF_TYPED_VALUE F198_4771 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 71L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_h */
EIF_TYPED_VALUE F198_4772 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 72L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_i */
EIF_TYPED_VALUE F198_4773 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 73L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_j */
EIF_TYPED_VALUE F198_4774 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 74L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_k */
EIF_TYPED_VALUE F198_4775 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 75L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_l */
EIF_TYPED_VALUE F198_4776 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 76L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_m */
EIF_TYPED_VALUE F198_4777 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 77L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_n */
EIF_TYPED_VALUE F198_4778 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 78L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_o */
EIF_TYPED_VALUE F198_4779 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 79L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_p */
EIF_TYPED_VALUE F198_4780 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 80L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_q */
EIF_TYPED_VALUE F198_4781 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 81L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_r */
EIF_TYPED_VALUE F198_4782 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 82L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_s */
EIF_TYPED_VALUE F198_4783 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 83L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_t */
EIF_TYPED_VALUE F198_4784 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 84L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_u */
EIF_TYPED_VALUE F198_4785 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 85L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_v */
EIF_TYPED_VALUE F198_4786 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 86L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_w */
EIF_TYPED_VALUE F198_4787 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 87L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_x */
EIF_TYPED_VALUE F198_4788 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 88L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_y */
EIF_TYPED_VALUE F198_4789 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 89L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.vk_z */
EIF_TYPED_VALUE F198_4790 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 90L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.keyeventf_extendedkey */
EIF_TYPED_VALUE F198_4791 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.keyeventf_keyup */
EIF_TYPED_VALUE F198_4792 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_absolute */
EIF_TYPED_VALUE F198_4793 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_move */
EIF_TYPED_VALUE F198_4794 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_leftdown */
EIF_TYPED_VALUE F198_4795 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_leftup */
EIF_TYPED_VALUE F198_4796 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_rightdown */
EIF_TYPED_VALUE F198_4797 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_rightup */
EIF_TYPED_VALUE F198_4798 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_middledown */
EIF_TYPED_VALUE F198_4799 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_middleup */
EIF_TYPED_VALUE F198_4800 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.mouseeventf_wheel */
EIF_TYPED_VALUE F198_4801 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_INPUT_CONSTANTS}.wheel_delta */
EIF_TYPED_VALUE F198_4802 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 120L);
	return r;
}

void EIF_Minit198 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
