/*
 * Code for class WEL_VK_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F462_7938(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7939(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7940(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7941(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7942(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7943(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7944(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7945(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7946(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7947(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7948(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7949(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7950(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7951(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7952(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7953(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7954(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7955(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7956(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7957(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7958(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7959(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7960(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7961(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7962(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7963(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7964(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7965(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7966(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7967(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7968(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7969(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7970(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7971(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7972(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7973(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7974(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7975(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7976(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7977(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7978(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7979(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7980(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7981(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7982(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7983(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7984(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7985(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7986(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7987(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7988(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7989(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7990(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7991(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7992(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7993(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7994(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7995(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7996(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7997(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7998(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_7999(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8000(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8001(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8002(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8003(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8004(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8005(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8006(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8007(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8008(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8009(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8010(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8011(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8012(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8013(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8014(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8015(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8016(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8017(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8018(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8019(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8020(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8021(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8022(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8023(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8024(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8025(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8026(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8027(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8028(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8029(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8030(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8031(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8032(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8033(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8034(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8035(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8036(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8037(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8038(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8039(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8040(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8041(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8042(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8043(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8044(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8045(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8046(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8047(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8048(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8049(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8050(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8051(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8052(EIF_REFERENCE);
extern EIF_TYPED_VALUE F462_8053(EIF_REFERENCE);
extern void EIF_Minit462(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_VK_CONSTANTS}.vk_lbutton */
EIF_TYPED_VALUE F462_7938 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_rbutton */
EIF_TYPED_VALUE F462_7939 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_cancel */
EIF_TYPED_VALUE F462_7940 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_mbutton */
EIF_TYPED_VALUE F462_7941 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_back */
EIF_TYPED_VALUE F462_7942 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_tab */
EIF_TYPED_VALUE F462_7943 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_clear */
EIF_TYPED_VALUE F462_7944 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_return */
EIF_TYPED_VALUE F462_7945 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_shift */
EIF_TYPED_VALUE F462_7946 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_control */
EIF_TYPED_VALUE F462_7947 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_menu */
EIF_TYPED_VALUE F462_7948 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_alt */
EIF_TYPED_VALUE F462_7949 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_pause */
EIF_TYPED_VALUE F462_7950 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_capital */
EIF_TYPED_VALUE F462_7951 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_escape */
EIF_TYPED_VALUE F462_7952 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_space */
EIF_TYPED_VALUE F462_7953 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_prior */
EIF_TYPED_VALUE F462_7954 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 33L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_next */
EIF_TYPED_VALUE F462_7955 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 34L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_end */
EIF_TYPED_VALUE F462_7956 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 35L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_home */
EIF_TYPED_VALUE F462_7957 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 36L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_left */
EIF_TYPED_VALUE F462_7958 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 37L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_up */
EIF_TYPED_VALUE F462_7959 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 38L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_right */
EIF_TYPED_VALUE F462_7960 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 39L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_down */
EIF_TYPED_VALUE F462_7961 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 40L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_select */
EIF_TYPED_VALUE F462_7962 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 41L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_print */
EIF_TYPED_VALUE F462_7963 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 42L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_execute */
EIF_TYPED_VALUE F462_7964 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 43L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_snapshot */
EIF_TYPED_VALUE F462_7965 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 44L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_insert */
EIF_TYPED_VALUE F462_7966 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 45L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_delete */
EIF_TYPED_VALUE F462_7967 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 46L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_help */
EIF_TYPED_VALUE F462_7968 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 47L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad0 */
EIF_TYPED_VALUE F462_7969 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 96L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad1 */
EIF_TYPED_VALUE F462_7970 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 97L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad2 */
EIF_TYPED_VALUE F462_7971 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 98L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad3 */
EIF_TYPED_VALUE F462_7972 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 99L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad4 */
EIF_TYPED_VALUE F462_7973 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 100L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad5 */
EIF_TYPED_VALUE F462_7974 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 101L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad6 */
EIF_TYPED_VALUE F462_7975 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 102L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad7 */
EIF_TYPED_VALUE F462_7976 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 103L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad8 */
EIF_TYPED_VALUE F462_7977 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 104L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numpad9 */
EIF_TYPED_VALUE F462_7978 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 105L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_multiply */
EIF_TYPED_VALUE F462_7979 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 106L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_add */
EIF_TYPED_VALUE F462_7980 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 107L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_separator */
EIF_TYPED_VALUE F462_7981 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 108L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_subtract */
EIF_TYPED_VALUE F462_7982 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 109L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_decimal */
EIF_TYPED_VALUE F462_7983 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 110L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_divide */
EIF_TYPED_VALUE F462_7984 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 111L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f1 */
EIF_TYPED_VALUE F462_7985 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 112L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f2 */
EIF_TYPED_VALUE F462_7986 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 113L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f3 */
EIF_TYPED_VALUE F462_7987 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 114L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f4 */
EIF_TYPED_VALUE F462_7988 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 115L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f5 */
EIF_TYPED_VALUE F462_7989 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 116L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f6 */
EIF_TYPED_VALUE F462_7990 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 117L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f7 */
EIF_TYPED_VALUE F462_7991 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 118L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f8 */
EIF_TYPED_VALUE F462_7992 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 119L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f9 */
EIF_TYPED_VALUE F462_7993 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 120L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f10 */
EIF_TYPED_VALUE F462_7994 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 121L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f11 */
EIF_TYPED_VALUE F462_7995 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 122L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f12 */
EIF_TYPED_VALUE F462_7996 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 123L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f13 */
EIF_TYPED_VALUE F462_7997 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 124L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f14 */
EIF_TYPED_VALUE F462_7998 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 125L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f15 */
EIF_TYPED_VALUE F462_7999 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 126L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f16 */
EIF_TYPED_VALUE F462_8000 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 127L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f17 */
EIF_TYPED_VALUE F462_8001 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f18 */
EIF_TYPED_VALUE F462_8002 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 129L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f19 */
EIF_TYPED_VALUE F462_8003 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 130L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f20 */
EIF_TYPED_VALUE F462_8004 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 131L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f21 */
EIF_TYPED_VALUE F462_8005 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 132L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f22 */
EIF_TYPED_VALUE F462_8006 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 133L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f23 */
EIF_TYPED_VALUE F462_8007 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 134L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f24 */
EIF_TYPED_VALUE F462_8008 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 135L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_numlock */
EIF_TYPED_VALUE F462_8009 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 144L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_scroll */
EIF_TYPED_VALUE F462_8010 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 145L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_lshift */
EIF_TYPED_VALUE F462_8011 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 160L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_rshift */
EIF_TYPED_VALUE F462_8012 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 161L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_lcontrol */
EIF_TYPED_VALUE F462_8013 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 162L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_rcontrol */
EIF_TYPED_VALUE F462_8014 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 163L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_lmenu */
EIF_TYPED_VALUE F462_8015 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 164L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_rmenu */
EIF_TYPED_VALUE F462_8016 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 165L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_apps */
EIF_TYPED_VALUE F462_8017 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 93L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_0 */
EIF_TYPED_VALUE F462_8018 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 48L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_1 */
EIF_TYPED_VALUE F462_8019 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 49L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_2 */
EIF_TYPED_VALUE F462_8020 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 50L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_3 */
EIF_TYPED_VALUE F462_8021 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 51L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_4 */
EIF_TYPED_VALUE F462_8022 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 52L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_5 */
EIF_TYPED_VALUE F462_8023 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 53L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_6 */
EIF_TYPED_VALUE F462_8024 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 54L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_7 */
EIF_TYPED_VALUE F462_8025 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 55L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_8 */
EIF_TYPED_VALUE F462_8026 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 56L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_9 */
EIF_TYPED_VALUE F462_8027 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 57L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_a */
EIF_TYPED_VALUE F462_8028 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_b */
EIF_TYPED_VALUE F462_8029 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 66L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_c */
EIF_TYPED_VALUE F462_8030 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 67L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_d */
EIF_TYPED_VALUE F462_8031 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 68L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_e */
EIF_TYPED_VALUE F462_8032 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 69L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_f */
EIF_TYPED_VALUE F462_8033 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 70L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_g */
EIF_TYPED_VALUE F462_8034 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 71L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_h */
EIF_TYPED_VALUE F462_8035 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 72L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_i */
EIF_TYPED_VALUE F462_8036 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 73L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_j */
EIF_TYPED_VALUE F462_8037 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 74L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_k */
EIF_TYPED_VALUE F462_8038 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 75L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_l */
EIF_TYPED_VALUE F462_8039 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 76L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_m */
EIF_TYPED_VALUE F462_8040 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 77L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_n */
EIF_TYPED_VALUE F462_8041 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 78L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_o */
EIF_TYPED_VALUE F462_8042 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 79L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_p */
EIF_TYPED_VALUE F462_8043 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 80L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_q */
EIF_TYPED_VALUE F462_8044 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 81L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_r */
EIF_TYPED_VALUE F462_8045 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 82L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_s */
EIF_TYPED_VALUE F462_8046 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 83L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_t */
EIF_TYPED_VALUE F462_8047 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 84L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_u */
EIF_TYPED_VALUE F462_8048 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 85L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_v */
EIF_TYPED_VALUE F462_8049 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 86L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_w */
EIF_TYPED_VALUE F462_8050 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 87L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_x */
EIF_TYPED_VALUE F462_8051 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 88L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_y */
EIF_TYPED_VALUE F462_8052 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 89L);
	return r;
}

/* {WEL_VK_CONSTANTS}.vk_z */
EIF_TYPED_VALUE F462_8053 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 90L);
	return r;
}

void EIF_Minit462 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
