/*
 * Code for class WEL_CAPABILITIES_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F466_8304(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8305(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8306(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8307(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8308(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8309(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8310(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8311(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8312(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8313(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8314(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8315(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8316(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8317(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8318(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8319(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8320(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8321(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8322(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8323(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8324(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8325(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8326(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8327(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8328(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8329(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8330(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8331(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8332(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8333(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8334(EIF_REFERENCE);
extern EIF_TYPED_VALUE F466_8335(EIF_REFERENCE);
extern void EIF_Minit466(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_CAPABILITIES_CONSTANTS}.driver_version */
EIF_TYPED_VALUE F466_8304 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.technology */
EIF_TYPED_VALUE F466_8305 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.horizontal_size */
EIF_TYPED_VALUE F466_8306 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.vertical_size */
EIF_TYPED_VALUE F466_8307 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.horizontal_resolution */
EIF_TYPED_VALUE F466_8308 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.vertical_resolution */
EIF_TYPED_VALUE F466_8309 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.logical_pixels_x */
EIF_TYPED_VALUE F466_8310 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 88L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.logical_pixels_y */
EIF_TYPED_VALUE F466_8311 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 90L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.bits_pixel */
EIF_TYPED_VALUE F466_8312 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.planes */
EIF_TYPED_VALUE F466_8313 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_brushes */
EIF_TYPED_VALUE F466_8314 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_pens */
EIF_TYPED_VALUE F466_8315 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_markers */
EIF_TYPED_VALUE F466_8316 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_fonts */
EIF_TYPED_VALUE F466_8317 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_colors */
EIF_TYPED_VALUE F466_8318 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 24L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.aspect_x */
EIF_TYPED_VALUE F466_8319 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 40L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.aspect_y */
EIF_TYPED_VALUE F466_8320 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 42L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.aspect_x_y */
EIF_TYPED_VALUE F466_8321 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 44L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.pdevice_size */
EIF_TYPED_VALUE F466_8322 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.clip_caps */
EIF_TYPED_VALUE F466_8323 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 36L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.size_palette */
EIF_TYPED_VALUE F466_8324 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 104L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.num_reserved */
EIF_TYPED_VALUE F466_8325 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 106L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.color_resolution */
EIF_TYPED_VALUE F466_8326 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 108L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.physical_offset_x */
EIF_TYPED_VALUE F466_8327 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 112L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.physical_offset_y */
EIF_TYPED_VALUE F466_8328 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 113L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.scaling_factor_x */
EIF_TYPED_VALUE F466_8329 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 114L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.scaling_factor_y */
EIF_TYPED_VALUE F466_8330 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 115L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.raster_caps */
EIF_TYPED_VALUE F466_8331 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 38L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.curve_caps */
EIF_TYPED_VALUE F466_8332 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.line_caps */
EIF_TYPED_VALUE F466_8333 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 30L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.polygonal_caps */
EIF_TYPED_VALUE F466_8334 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_CAPABILITIES_CONSTANTS}.text_caps */
EIF_TYPED_VALUE F466_8335 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 34L);
	return r;
}

void EIF_Minit466 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
