/*
 * Code for class WEL_LIST_VIEW_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F306_5887(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5888(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5889(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5890(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5891(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5892(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5893(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5894(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5895(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5896(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5897(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5898(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5899(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5900(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5901(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5902(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5903(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5904(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5905(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5906(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5907(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5908(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5909(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5910(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5911(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5912(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5913(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5914(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5915(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5916(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5917(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5918(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5919(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5920(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5921(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5922(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5923(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5924(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5925(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5926(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5927(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5928(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5929(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5930(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5931(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5932(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5933(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5934(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5935(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5936(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5937(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5938(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5939(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5940(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5941(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5942(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5943(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5944(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5945(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5946(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5947(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5948(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5949(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5950(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5951(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5952(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5953(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5954(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5955(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5956(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5957(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5958(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5959(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5960(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5961(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5962(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5963(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5964(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5965(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5966(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5967(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5968(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5969(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5970(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5971(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5972(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5973(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5974(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5975(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5976(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5977(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5978(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5979(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5980(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5981(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5982(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5983(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5984(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5985(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5986(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5987(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5988(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5989(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5990(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5991(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5992(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5993(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5994(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5995(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5996(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5997(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5998(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_5999(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6000(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6001(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6002(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6003(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6004(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6005(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6006(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6007(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6008(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6009(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6010(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6011(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6012(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6013(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6014(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6015(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6016(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6017(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6018(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6019(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6020(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6021(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6022(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6023(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6024(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6025(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6026(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6027(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6028(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6029(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6030(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6031(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6032(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6033(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6034(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6035(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6036(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6037(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6038(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6039(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6040(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6041(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6042(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6043(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6044(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6045(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6046(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6047(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6048(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6049(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6050(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6051(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6052(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6053(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6054(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6055(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6056(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6057(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6058(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6059(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6060(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6061(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6062(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6063(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6064(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6065(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6066(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6067(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6068(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6069(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6070(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6071(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6072(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6073(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6074(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6075(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6076(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6077(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6078(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6079(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6080(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6081(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6082(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6083(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6084(EIF_REFERENCE);
extern EIF_TYPED_VALUE F306_6085(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F306_6086(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F306_6087(EIF_REFERENCE, EIF_TYPED_VALUE);
extern EIF_TYPED_VALUE F306_6088(EIF_REFERENCE, EIF_TYPED_VALUE);
extern void EIF_Minit306(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_icon */
EIF_TYPED_VALUE F306_5887 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_report */
EIF_TYPED_VALUE F306_5888 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_smallicon */
EIF_TYPED_VALUE F306_5889 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_list */
EIF_TYPED_VALUE F306_5890 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_alignleft */
EIF_TYPED_VALUE F306_5891 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_aligntop */
EIF_TYPED_VALUE F306_5892 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_autoarrange */
EIF_TYPED_VALUE F306_5893 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_editlabels */
EIF_TYPED_VALUE F306_5894 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_nocolumnheader */
EIF_TYPED_VALUE F306_5895 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16384L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_nosortheader */
EIF_TYPED_VALUE F306_5896 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32768L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_nolabelwrap */
EIF_TYPED_VALUE F306_5897 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_noscroll */
EIF_TYPED_VALUE F306_5898 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8192L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ownerdrawfixed */
EIF_TYPED_VALUE F306_5899 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_shareimagelists */
EIF_TYPED_VALUE F306_5900 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_showselalways */
EIF_TYPED_VALUE F306_5901 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_singlesel */
EIF_TYPED_VALUE F306_5902 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_sortascending */
EIF_TYPED_VALUE F306_5903 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_sortdescending */
EIF_TYPED_VALUE F306_5904 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_checkboxes */
EIF_TYPED_VALUE F306_5905 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_flatsb */
EIF_TYPED_VALUE F306_5906 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_fullrowselect */
EIF_TYPED_VALUE F306_5907 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_gridlines */
EIF_TYPED_VALUE F306_5908 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_headerdragdrop */
EIF_TYPED_VALUE F306_5909 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_infotip */
EIF_TYPED_VALUE F306_5910 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_labeltip */
EIF_TYPED_VALUE F306_5911 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16384L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_multiworkareas */
EIF_TYPED_VALUE F306_5912 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8192L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_oneclickactivate */
EIF_TYPED_VALUE F306_5913 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_regional */
EIF_TYPED_VALUE F306_5914 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_subitemimages */
EIF_TYPED_VALUE F306_5915 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_trackselect */
EIF_TYPED_VALUE F306_5916 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_twoclickactivate */
EIF_TYPED_VALUE F306_5917 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 128L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_underlinecold */
EIF_TYPED_VALUE F306_5918 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_underlinehot */
EIF_TYPED_VALUE F306_5919 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvs_ex_doublebuffer */
EIF_TYPED_VALUE F306_5920 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65536L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_arrange */
EIF_TYPED_VALUE F306_5921 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4118L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_createdragimage */
EIF_TYPED_VALUE F306_5922 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4129L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_deleteallitems */
EIF_TYPED_VALUE F306_5923 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4105L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_deletecolumn */
EIF_TYPED_VALUE F306_5924 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4124L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_deleteitem */
EIF_TYPED_VALUE F306_5925 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4104L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_editlabel */
EIF_TYPED_VALUE F306_5926 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4214L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_ensurevisible */
EIF_TYPED_VALUE F306_5927 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4115L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_finditem */
EIF_TYPED_VALUE F306_5928 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4179L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getbkcolor */
EIF_TYPED_VALUE F306_5929 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4096L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getcallbackmask */
EIF_TYPED_VALUE F306_5930 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4106L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getcolumn */
EIF_TYPED_VALUE F306_5931 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4191L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getcolumnwidth */
EIF_TYPED_VALUE F306_5932 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4125L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getcountperpage */
EIF_TYPED_VALUE F306_5933 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4136L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_geteditcontrol */
EIF_TYPED_VALUE F306_5934 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4120L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getimagelist */
EIF_TYPED_VALUE F306_5935 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4098L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getisearchstring */
EIF_TYPED_VALUE F306_5936 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4213L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitem */
EIF_TYPED_VALUE F306_5937 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4171L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemcount */
EIF_TYPED_VALUE F306_5938 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4100L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemposition */
EIF_TYPED_VALUE F306_5939 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4112L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemrect */
EIF_TYPED_VALUE F306_5940 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4110L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemspacing */
EIF_TYPED_VALUE F306_5941 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4147L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemstate */
EIF_TYPED_VALUE F306_5942 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4140L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getitemtext */
EIF_TYPED_VALUE F306_5943 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4211L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getnextitem */
EIF_TYPED_VALUE F306_5944 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4108L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getorigin */
EIF_TYPED_VALUE F306_5945 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4137L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getselectedcount */
EIF_TYPED_VALUE F306_5946 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4146L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getstringwidth */
EIF_TYPED_VALUE F306_5947 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4183L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gettextbkcolor */
EIF_TYPED_VALUE F306_5948 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4133L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gettextcolor */
EIF_TYPED_VALUE F306_5949 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4131L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gettopindex */
EIF_TYPED_VALUE F306_5950 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4135L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getviewrect */
EIF_TYPED_VALUE F306_5951 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4130L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_hittest */
EIF_TYPED_VALUE F306_5952 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4114L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_insertcolumn */
EIF_TYPED_VALUE F306_5953 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4193L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_insertitem */
EIF_TYPED_VALUE F306_5954 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4173L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_redrawitems */
EIF_TYPED_VALUE F306_5955 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4117L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_scroll */
EIF_TYPED_VALUE F306_5956 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4116L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setbkcolor */
EIF_TYPED_VALUE F306_5957 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4097L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setcallbackmask */
EIF_TYPED_VALUE F306_5958 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4107L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setcolumn */
EIF_TYPED_VALUE F306_5959 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4192L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setcolumnwidth */
EIF_TYPED_VALUE F306_5960 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4126L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setimagelist */
EIF_TYPED_VALUE F306_5961 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4099L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitem */
EIF_TYPED_VALUE F306_5962 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4172L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitemcount */
EIF_TYPED_VALUE F306_5963 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4143L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitemposition */
EIF_TYPED_VALUE F306_5964 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4111L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitemposition32 */
EIF_TYPED_VALUE F306_5965 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4145L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitemstate */
EIF_TYPED_VALUE F306_5966 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4139L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setitemtext */
EIF_TYPED_VALUE F306_5967 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4212L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_settextbkcolor */
EIF_TYPED_VALUE F306_5968 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4134L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_settextcolor */
EIF_TYPED_VALUE F306_5969 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4132L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_settooltips */
EIF_TYPED_VALUE F306_5970 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4170L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_sortitems */
EIF_TYPED_VALUE F306_5971 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4144L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setunicodeformat */
EIF_TYPED_VALUE F306_5972 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8197L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_update */
EIF_TYPED_VALUE F306_5973 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4138L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_approximateviewrect */
EIF_TYPED_VALUE F306_5974 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4160L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getbkimage */
EIF_TYPED_VALUE F306_5975 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4165L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getcolumnorderarray */
EIF_TYPED_VALUE F306_5976 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4155L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getextendedlistviewstyle */
EIF_TYPED_VALUE F306_5977 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4151L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setextendedlistviewstyle */
EIF_TYPED_VALUE F306_5978 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4150L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getheader */
EIF_TYPED_VALUE F306_5979 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4127L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gethotcursor */
EIF_TYPED_VALUE F306_5980 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4159L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gethotitem */
EIF_TYPED_VALUE F306_5981 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4157L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_gethovertime */
EIF_TYPED_VALUE F306_5982 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4168L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getnumberofworkareas */
EIF_TYPED_VALUE F306_5983 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4169L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getsubitemrect */
EIF_TYPED_VALUE F306_5984 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4152L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_getworkareas */
EIF_TYPED_VALUE F306_5985 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4166L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setbkimage */
EIF_TYPED_VALUE F306_5986 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4164L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_sethotcursor */
EIF_TYPED_VALUE F306_5987 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4158L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_sethotitem */
EIF_TYPED_VALUE F306_5988 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4156L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_sethovertime */
EIF_TYPED_VALUE F306_5989 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4167L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setworkareas */
EIF_TYPED_VALUE F306_5990 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4161L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_setselectionmark */
EIF_TYPED_VALUE F306_5991 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4163L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvm_subitemhittest */
EIF_TYPED_VALUE F306_5992 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4153L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_begindrag */
EIF_TYPED_VALUE F306_5993 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -109L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_beginlabeledit */
EIF_TYPED_VALUE F306_5994 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -175L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_beginrdrag */
EIF_TYPED_VALUE F306_5995 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -111L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_columnclick */
EIF_TYPED_VALUE F306_5996 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -108L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_deleteallitems */
EIF_TYPED_VALUE F306_5997 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -104L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_deleteitem */
EIF_TYPED_VALUE F306_5998 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -103L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_endlabeledit */
EIF_TYPED_VALUE F306_5999 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -176L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_getdispinfo */
EIF_TYPED_VALUE F306_6000 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -177L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_insertitem */
EIF_TYPED_VALUE F306_6001 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -102L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_itemchanged */
EIF_TYPED_VALUE F306_6002 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -101L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_itemchanging */
EIF_TYPED_VALUE F306_6003 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -100L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_keydown */
EIF_TYPED_VALUE F306_6004 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -155L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_setdispinfo */
EIF_TYPED_VALUE F306_6005 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -178L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_getinfotip */
EIF_TYPED_VALUE F306_6006 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -157L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvn_marqueebegin */
EIF_TYPED_VALUE F306_6007 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -156L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchanging */
EIF_TYPED_VALUE F306_6008 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -300L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchanginga */
EIF_TYPED_VALUE F306_6009 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -300L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchangingw */
EIF_TYPED_VALUE F306_6010 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -320L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchanged */
EIF_TYPED_VALUE F306_6011 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -301L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchangeda */
EIF_TYPED_VALUE F306_6012 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -301L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemchangedw */
EIF_TYPED_VALUE F306_6013 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -321L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemclick */
EIF_TYPED_VALUE F306_6014 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -302L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemclicka */
EIF_TYPED_VALUE F306_6015 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -302L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemclickw */
EIF_TYPED_VALUE F306_6016 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -322L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemdblclick */
EIF_TYPED_VALUE F306_6017 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -303L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemdblclicka */
EIF_TYPED_VALUE F306_6018 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -303L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_itemdblclickw */
EIF_TYPED_VALUE F306_6019 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -323L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_dividerdblclick */
EIF_TYPED_VALUE F306_6020 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -305L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_dividerdblclicka */
EIF_TYPED_VALUE F306_6021 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -305L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_dividerdblclickw */
EIF_TYPED_VALUE F306_6022 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -325L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_begintrack */
EIF_TYPED_VALUE F306_6023 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -306L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_begintracka */
EIF_TYPED_VALUE F306_6024 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -306L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_begintrackw */
EIF_TYPED_VALUE F306_6025 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -326L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_endtrack */
EIF_TYPED_VALUE F306_6026 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -307L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_endtracka */
EIF_TYPED_VALUE F306_6027 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -307L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_endtrackw */
EIF_TYPED_VALUE F306_6028 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -327L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_track */
EIF_TYPED_VALUE F306_6029 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -308L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_tracka */
EIF_TYPED_VALUE F306_6030 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -308L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_trackw */
EIF_TYPED_VALUE F306_6031 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -328L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_getdispinfo */
EIF_TYPED_VALUE F306_6032 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -309L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_getdispinfoa */
EIF_TYPED_VALUE F306_6033 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -309L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_getdispinfow */
EIF_TYPED_VALUE F306_6034 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -329L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_begindrag */
EIF_TYPED_VALUE F306_6035 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -310L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.hdn_enddrag */
EIF_TYPED_VALUE F306_6036 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -311L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_above */
EIF_TYPED_VALUE F306_6037 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_below */
EIF_TYPED_VALUE F306_6038 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_nowhere */
EIF_TYPED_VALUE F306_6039 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_onitemicon */
EIF_TYPED_VALUE F306_6040 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_onitemlabel */
EIF_TYPED_VALUE F306_6041 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_onitemstateicon */
EIF_TYPED_VALUE F306_6042 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_toleft */
EIF_TYPED_VALUE F306_6043 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvht_toright */
EIF_TYPED_VALUE F306_6044 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcf_fmt */
EIF_TYPED_VALUE F306_6045 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcf_subitem */
EIF_TYPED_VALUE F306_6046 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcf_text */
EIF_TYPED_VALUE F306_6047 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcf_width */
EIF_TYPED_VALUE F306_6048 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcf_image */
EIF_TYPED_VALUE F306_6049 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcfmt_right */
EIF_TYPED_VALUE F306_6050 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcfmt_center */
EIF_TYPED_VALUE F306_6051 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcfmt_left */
EIF_TYPED_VALUE F306_6052 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvcfmt_justifymask */
EIF_TYPED_VALUE F306_6053 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvscw_autosize */
EIF_TYPED_VALUE F306_6054 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvscw_autosize_useheader */
EIF_TYPED_VALUE F306_6055 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvif_text */
EIF_TYPED_VALUE F306_6056 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvif_image */
EIF_TYPED_VALUE F306_6057 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvif_param */
EIF_TYPED_VALUE F306_6058 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvif_state */
EIF_TYPED_VALUE F306_6059 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvis_cut */
EIF_TYPED_VALUE F306_6060 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvis_drophilited */
EIF_TYPED_VALUE F306_6061 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvis_focused */
EIF_TYPED_VALUE F306_6062 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvis_selected */
EIF_TYPED_VALUE F306_6063 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_above */
EIF_TYPED_VALUE F306_6064 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 256L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_all */
EIF_TYPED_VALUE F306_6065 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_below */
EIF_TYPED_VALUE F306_6066 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 512L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_toleft */
EIF_TYPED_VALUE F306_6067 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1024L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_toright */
EIF_TYPED_VALUE F306_6068 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2048L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_cut */
EIF_TYPED_VALUE F306_6069 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_drophilited */
EIF_TYPED_VALUE F306_6070 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_focused */
EIF_TYPED_VALUE F306_6071 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvni_selected */
EIF_TYPED_VALUE F306_6072 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvsil_normal */
EIF_TYPED_VALUE F306_6073 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvsil_small */
EIF_TYPED_VALUE F306_6074 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvsil_state */
EIF_TYPED_VALUE F306_6075 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvfi_param */
EIF_TYPED_VALUE F306_6076 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvfi_partial */
EIF_TYPED_VALUE F306_6077 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvfi_string */
EIF_TYPED_VALUE F306_6078 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvfi_wrap */
EIF_TYPED_VALUE F306_6079 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 32L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvfi_nearestxy */
EIF_TYPED_VALUE F306_6080 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 64L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvir_bounds */
EIF_TYPED_VALUE F306_6081 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvir_icon */
EIF_TYPED_VALUE F306_6082 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvir_label */
EIF_TYPED_VALUE F306_6083 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.lvir_selectbounds */
EIF_TYPED_VALUE F306_6084 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_LIST_VIEW_CONSTANTS}.is_valid_list_view_flag */
EIF_TYPED_VALUE F306_6085 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "is_valid_list_view_flag";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_INTEGER_32 ti4_5;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 305, Current, 0, 1, 5847);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(305, Current, 5847);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(Current, 0, 0x04000000, 1,0); /* Result */
	
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 221, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 222, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 223, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 224, dtype))(Current)).it_i4);
	ti4_5 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 225, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4)) || (EIF_BOOLEAN)(arg1 == ti4_5));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

/* {WEL_LIST_VIEW_CONSTANTS}.valid_lvcfmt_constant */
EIF_TYPED_VALUE F306_6086 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "valid_lvcfmt_constant";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 305, Current, 0, 1, 5848);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(305, Current, 5848);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(Current, 0, 0x04000000, 1,0); /* Result */
	
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 197, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 196, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 195, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 198, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

/* {WEL_LIST_VIEW_CONSTANTS}.valid_lvis_constants */
EIF_TYPED_VALUE F306_6087 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "valid_lvis_constants";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 305, Current, 0, 1, 5849);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(305, Current, 5849);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(Current, 0, 0x04000000, 1,0); /* Result */
	
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 205, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 206, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 207, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 208, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

/* {WEL_LIST_VIEW_CONSTANTS}.valid_lvir_constant */
EIF_TYPED_VALUE F306_6088 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "valid_lvir_constant";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 305, Current, 0, 1, 5850);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(305, Current, 5850);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(Current, 0, 0x04000000, 1,0); /* Result */
	
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 226, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 227, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 228, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(305, 229, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

void EIF_Minit306 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
